version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"

  todo-app:
    build: .
    container_name: todo_web_app
    environment:
      # Sửa Server=sqlserver (tên service) và Database=TodoDbLocal
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TodoDbLocal;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver